---
title: "maps-ggplot"
author: "Aryan Raval"
format: html
editor: visual
---

```{r}
library(tidyverse)

```


```{r}
library(mdsr)
library(sf)
```


```{r}
library(ggspatial)
library(leaflet)
library(tidygeocoder)
library(mapproj)
```


```{r}
library(maps)

```



```{r}
addresses<- tibble(address=c("Smith College", "2 Tyler Ct, Northampton, MA 01060", "Holyoke Community College")) |>
geocode(address, method="osm") |>
  mutate(name = c("Smith College","McConnell Hall","Holyoke Community College"))

addresses

```

```{r}
ggplot(addresses) +
  geom_point(aes(long,lat)) 

```

```{r}
ma_counties <- map_data("county", "massachusetts") %>% 
  select( long, lat, group, id = subregion)

head(ma_counties)
```

```{r}
ma_counties |> ggplot(aes(long,lat,group=group))+
  geom_polygon(fill = "white", colour = "grey50")+
  geom_point()  
```

```{r}
#coord_sf()
ma_counties |> ggplot(aes(long,lat,group=group))+
  geom_polygon(fill = "white", colour = "grey50")+
  geom_point()+
  coord_sf()
```

```{r}
ma_cities <- us.cities |>
  filter(country.etc =="MA") |>
  select(name, long, lat)

head(ma_cities)
```

```{r}
ma_counties |> ggplot(aes(long,lat))+
  geom_polygon(fill = "white", colour = "grey50",aes(group=group)) +
  #geom_point(data=ma_cities,.......)
  
  #This is the default mapping. Think GPS
 coord_sf(default_crs= st_crs(4326) )
```

```{r}
```

```{r}
```

```{r}
```
